#*/-kernel/cargo.toml
[package]
name = "taiga-os-kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "kernel"
test = false
bench = false

[profile.release]
strip = true

[dependencies]
