#*/-kernel/cargo.toml
[package]
name = "taiga-os-kernel"
version = "0.0.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "kernel"
test = false
bench = false

[lib]
path = "src/lib.rs"
name = "taiga"
test = false
bench = false


[profile.release]
opt-level = 0
strip = "debuginfo"
lto = true
panic = 'unwind'
incremental = true
codegen-units = 16
rpath = false


[dependencies]