[build]
target = "x64_kernel_target.json"
target-dir = "../../target"

[target."x64_kernel_target.json"]
rustflags = ["-C", "relocation-model=static", "-C", "link-args=-no-pie" ,"-C", "link-arg=-Tx64_kernel_linker.ld"]

[unstable]
build-std = ["core", "compiler_builtins"]